apiVersion: v1
data:
  dragent.yaml: |
    new_k8s: true
    k8s_cluster_name: your-cluster-name
    jmx:
      enabled: false
    metrics_excess_log: true
    app_checks_enabled: false
    10s_flush_enable: true
    use_promscrape: true
    prometheus:
      enabled: true
      histograms: true
      ingest_raw: true
      ingest_calculated: false
      interval: 10
      log_errors: true
      max_metrics: 3000
      max_metrics_per_process: 20000
      process_filter:
      - include:
          kubernetes.pod.annotation.prometheus.io/scrape: true
          conf:
              path: "{kubernetes.pod.annotation.prometheus.io/path}"
              port: "{kubernetes.pod.annotation.prometheus.io/port}"
              tags:
                app: "{kubernetes.pod.label.app}"
    snaplen: 512
    tags: role:cluster
kind: ConfigMap
metadata:
    labels:
      app: sysdig-agent
    name: sysdig-agent
    namespace: sysdig-agent
    