---
apiVersion: v1
kind: App
name: "Nginx-Ingress"
keywords: 
  - Kubernetes
  - Available
availableVersions: 
  - '2.7.0'
shortDescription: "The open source web server that powers 400 million websites."
description: |
  NGINX Ingress Controller is a best-in-class traffic management solution for cloudâ€‘native apps in Kubernetes and containerized environments.
icon: https://upload.wikimedia.org/wikipedia/commons/c/c5/Nginx_logo.svg
website: https://www.nginx.com/products/nginx-ingress-controller/
available: true